try:
    n=(int(input()))
except:
    print("invalid number")
print(5)






n1=(input())
n2=(input())
try:
    print(int(n1)+int(n2))
except Exception as e:
    print(e)

print("try except is succesfully executed")
